export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const INITIATE_LOGOUT_USER = 'INITIATE_LOGOUT_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const AUTO_LOGOUT = 'AUTO_LOGOUT';
export const CHECK_STATE = 'CHECK_STATE';
export const REGISTRATION = 'REGISTRATION';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const ACTIVATE_USER = 'ACTIVATE_USER';
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS';
export const ACTIVATE_USER_ERROR = 'ACTIVATE_USER_ERROR';
export const CLEAR_AUTH = 'CLEAR_AUTH';

export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_ALL_BOOKS = 'GET_ALL_BOOKS';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const ADD_BOOK = 'ADD_BOOK';
export const GET_BOOK = 'GET_BOOK';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const MOVE_BOOK = 'MOVE_BOOK';
export const LOAN_BOOK = 'LOAN_BOOK';
export const ORDER_BOOK = 'ORDER_BOOK';

export const GET_STATISTIC = 'GET_STATISTIC';
export const GET_STATISTIC_SUCCESS = 'GET_STATISTIC_SUCCESS';

export const SET_LOADING_INDICATOR = 'SET_LOADING_INDICATOR';

export const SET_OPEN_SNACKBAR = 'SET_OPEN_SNACKBAR';

export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS';
export const SET_SELECTED_DEPARTMENT = 'SET_SELECTED_DEPARTMENT';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';

export const GET_AUTHORS = 'GET_AUTHORS';
export const GET_AUTHORS_SUCCESS = 'GET_AUTHORS_SUCCESS';
export const ADD_AUTHOR = 'ADD_AUTHOR';
export const UPDATE_AUTHOR = 'UPDATE_AUTHOR';
export const DELETE_AUTHOR = 'DELETE_AUTHOR';

export const GET_GENRES = 'GET_GENRES';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const SET_SELECTED_GENRES = 'SET_SELECTED_GENRES';

export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS';

export const GET_ALL_LIBRARIANS = 'GET_ALL_LIBRARIANS';
export const GET_ALL_LIBRARIANS_SUCCESS = 'GET_ALL_LIBRARIANS_SUCCESS';
