export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const INITIATE_LOGOUT_USER = 'INITIATE_LOGOUT_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const AUTO_LOGOUT = 'AUTO_LOGOUT';
export const CHECK_STATE = 'CHECK_STATE';
